from __future__ import annotations

PAC_VERTEX_STRIDE = 32
PAC_POSITION_OFFSET = 0
PAC_NORMAL_OFFSET = 12
PAC_TANGENT_W_OFFSET = 15
PAC_UV_OFFSET = 16
PAC_COLOR_OFFSET = 20
PAC_BONE_INDEX_OFFSET = 24
PAC_BONE_WEIGHT_OFFSET = 28

PAM_VERTEX_STRIDE = 28
PAM_TAG_OFFSET = 0
PAM_POSITION_OFFSET = 4
PAM_UV_OFFSET = 16
PAM_NORMAL_OFFSET = 20
PAM_TANGENT_W_OFFSET = 23
PAM_UV1_OFFSET = 24
